name: catbreeds
description: The best app to learn everything about cat breeds
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.3
  cached_network_image: ^3.3.1
  dio: ^5.4.1
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  go_router: ^13.2.1
  infinite_scroll_pagination: ^4.0.0
  json_annotation: ^4.8.1
  riverbloc: ^2.2.0
  meta: ^1.11.0
  collection: ^1.18.0
  rxdart: ^0.27.7
  flex_color_scheme: ^7.3.1
  google_fonts: ^6.2.1
  envied: ^0.5.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  freezed: ^2.4.7
  go_router_builder: ^2.4.1
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  bloc_test: ^9.1.6
  test: ^1.24.9
  build_runner: ^2.4.8
  build_verify: ^3.1.0
  flutter_launcher_icons: ^0.13.1
  envied_generator: ^0.5.3

flutter:
  uses-material-design: true
  assets:
    - assets/google_fonts/
    - assets/images/

flutter_launcher_icons:
  image_path: "assets/images/icon.png"
  android: "ic_launcher"
  web:
    generate: true
    image_path: "assets/images/icon.png"
  windows:
    generate: true
    image_path: "assets/images/icon.png"
    icon_size: 48
