name: Flutter Web

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.3'
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Build Web
      run: flutter build web --base-href=/catbreeds/

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: build/web
